# Generated by Django 5.0.6 on 2024-06-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=3)),
                ('simbolo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subcuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingresos'), ('EGRESO', 'Egresos'), ('OTRO', 'Otro')], default='OTRO', max_length=7)),
                ('desc', models.CharField(max_length=250)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcontame.cuenta')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcontame.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcontame.asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appcontame.subcuenta')),
            ],
        ),
    ]
